# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

accident_types = [
	{accident: "Acidente de Viação"},
	{accident: "Atropelamento"},
	{accident: "Falhas Mecânicas"},
	{accident: "Furto/Roubo"},
	{accident: "Incêndio"},
	{accident: "Quebra de vidros"}
] 

accident_types.each do |attributes|
  AccidentType.where(accident: attributes[:accident]).first_or_initialize.tap do |t|
  t.save!
  end
end


countries = [
	{country: "África do Sul"},
	{country: "Albânia"},
	{country: "Alemanha"},
	{country: "Alto Volta"},
	{country: "Andorra"},
	{country: "Angola"},
	{country: "Antígua"},
	{country: "Antilhas"},
	{country: "Arábia Saudita"},
	{country: "Argélia"},
	{country: "Argentina"},
	{country: "Austrália"},
	{country: "Áustria"},
	{country: "Bahamas"},
	{country: "Bahrein"},
	{country: "Bangladesh"},
	{country: "Barbados"},
	{country: "Bélgica"},
	{country: "Belize"},
	{country: "Benim"},
	{country: "Bermudas"},
	{country: "Bielorrusia"},
	{country: "Birmânia"},
	{country: "Bolívia"},
	{country: "Botswana"},
	{country: "Brasil"},
	{country: "Brunei"},
	{country: "Bulgária"},
	{country: "Burkina Faso"},
	{country: "Burundi"},
	{country: "Butão"},
	{country: "Cabo Verde"},
	{country: "Camarões"},
	{country: "Cambodja"},
	{country: "Canadá"},
	{country: "Chade"},
	{country: "Chile"},
	{country: "China (Formosa)"},
	{country: "Chipre"},
	{country: "Colômbia"},
	{country: "Congo"},
	{country: "Coreia do Norte"},
	{country: "Coreia do Sul"},
	{country: "Costa do Marfim"},
	{country: "Costa Rica"},
	{country: "Cuba"},
	{country: "Dinamarca"},
	{country: "Djibouti"},
	{country: "Dominica"},
	{country: "Egipto"},
	{country: "El Salvador"},
	{country: "Emiratos Árabes Unidos"},
	{country: "Equador"},
	{country: "Eslovaquia"},
	{country: "Eslovenia"},
	{country: "Espanha"},
	{country: "Estados Unidos"},
	{country: "Estónia"},
	{country: "Etiópia"},
	{country: "Federação Russa"},
	{country: "Filipinas"},
	{country: "Finlândia"},
	{country: "França"},
	{country: "Gabão"},
	{country: "Gâmbia"},
	{country: "Ghana"},
	{country: "Gibraltar"},
	{country: "Grã-Bretanha"},
	{country: "Granada"},
	{country: "Grécia"},
	{country: "Guatemala"},
	{country: "Guiana"},
	{country: "Guiana Francesa"},
	{country: "Guiné"},
	{country: "Guiné Equatorial"},
	{country: "Guiné-Bissau"},
	{country: "Haiti"},
	{country: "Holanda"},
	{country: "Honduras"},
	{country: "Hungria"},
	{country: "Iémen"},
	{country: "Iémen do Sul"},
	{country: "Índia"},
	{country: "Indonésia"},
	{country: "Irão"},
	{country: "Iraque"},
	{country: "Irlanda"},
	{country: "Islândia"},
	{country: "Israel"},
	{country: "Itália"},
	{country: "Jamaica"},
	{country: "Japão"},
	{country: "Jordânia"},
	{country: "Jugoslávia"},
	{country: "Koweit"},
	{country: "Laos"},
	{country: "Lesoto"},
	{country: "Letonia"},
	{country: "Líbano"},
	{country: "Libéria"},
	{country: "Líbia"},
	{country: "Liechtenstein"},
	{country: "Lituania"},
	{country: "Luxemburgo"},
	{country: "Macau"},
	{country: "Madagáscar"},
	{country: "Malásia"},
	{country: "Malawi"},
	{country: "Maldivas"},
	{country: "Mali"},
	{country: "Malta"},
	{country: "Marrocos"},
	{country: "Mauricias"},
	{country: "Mauritânia"},
	{country: "México"},
	{country: "Moçambique"},
	{country: "Mónaco"},
	{country: "Mongólia"},
	{country: "Namíbia"},
	{country: "Nepal"},
	{country: "Nicarágua"},
	{country: "Níger"},
	{country: "Nigéria"},
	{country: "Noruega"},
	{country: "Nova Guiné"},
	{country: "Nova Zelândia"},
	{country: "Omã"},
	{country: "Panamá"},
	{country: "Paquistão"},
	{country: "Paraguai"},
	{country: "Peru"},
	{country: "Polónia"},
	{country: "Portugal"},
	{country: "Qatar"},
	{country: "Quénia"},
	{country: "Rep. Centro-Africana"},
	{country: "Rep. Dominicana"},
	{country: "Rep. Popular China"},
	{country: "República Checa"},
	{country: "Roménia"},
	{country: "Ruanda"},
	{country: "S. Marinho"},
	{country: "S. Tomé e Príncipe"},
	{country: "Senegal"},
	{country: "Serra Leoa"},
	{country: "Seychelles"},
	{country: "Singapura"},
	{country: "Síria"},
	{country: "Somália"},
	{country: "Sri Lanka"},
	{country: "Suazilândia"},
	{country: "Sudão"},
	{country: "Suécia"},
	{country: "Suiça"},
	{country: "Suriname"},
	{country: "Tailândia"},
	{country: "Tanzânia"},
	{country: "Timor Leste"},
	{country: "Togo"},
	{country: "Trinidad e Tobago"},
	{country: "Tunísia"},
	{country: "Turquia"},
	{country: "Ucrânia"},
	{country: "Uganda"},
	{country: "Uruguai"},
	{country: "Vaticano"},
	{country: "Venezuela"},
	{country: "Vietname"},
	{country: "Zaire"},
	{country: "Zâmbia"},
	{country: "Zimbabwé"}
]

countries.each do |attributes|
  Country.where(country: attributes[:country]).first_or_initialize.tap do |a|
  a.save!
  end
end

vehicle_categories = [
	{category: "Ambulancia ligeiro"},
	{category: "Auto Caravana"},
	{category: "Autocarro ate 20 lugares"},
	{category: "Autocarro com mais 20 lugares"},
	{category: "Camiao ate 20 Ton PB"},
	{category: "Camiao com mais 20 Ton PB"},
	{category: "Ciclomotor"},
	{category: "Ligeiro bombeiros"},
	{category: "Ligeiro de instruçao"},
	{category: "Ligeiro mercadorias"},
	{category: "Ligeiro passageiros"},
	{category: "Motociclo"},
	{category: "Motociclo ciclomotor instruçao"},
	{category: "Pesado bombeiros"},
	{category: "Pesado de instruçao"},
	{category: "Reboque agricola"},
	{category: "Transporte colectivo urbano"},
	{category: "Veiculo classico"}
]

vehicle_categories.each do |attributes|
  VehicleCategory.where(category: attributes[:category]).first_or_initialize.tap do |c|
  c.save!
  end
end
